import { useState } from 'react';
import { Send, Upload, X, Image as ImageIcon } from 'lucide-react';
import { createOrder, uploadProductImage } from '../api/client';
import Button from '../components/Button';
import './CustomOrder.css';

export default function CustomOrder() {
  const [formData, setFormData] = useState({
    customer_name: '',
    customer_email: '',
    customer_phone: '',
    address: '',
    department: 'Atlantico',
    custom_description: '',
    reference_images: [],
  });
  
  const [loading, setLoading] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [success, setSuccess] = useState(false);
  const [error, setError] = useState('');

  const handleImageUpload = async (e) => {
    const files = Array.from(e.target.files);
    if (!files.length) return;
    
    setUploading(true);
    setError('');
    try {
      const uploadedUrls = [];
      for (const file of files) {
        const { image_url } = await uploadProductImage(file);
        uploadedUrls.push(image_url);
      }
      setFormData(prev => ({
        ...prev,
        reference_images: [...prev.reference_images, ...uploadedUrls]
      }));
    } catch (err) {
      setError(err.message || 'Error al subir algunas imágenes');
    } finally {
      setUploading(false);
      e.target.value = ''; // Reset input
    }
  };

  const removeImage = (indexToRemove) => {
    setFormData(prev => ({
      ...prev,
      reference_images: prev.reference_images.filter((_, idx) => idx !== indexToRemove)
    }));
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    
    // Construct address
    const fullAddress = `${formData.address}, ${formData.department}`;
    
    try {
      await createOrder({
        customer_name: formData.customer_name.trim(),
        customer_email: formData.customer_email.trim(),
        customer_phone: formData.customer_phone.trim(),
        address: fullAddress,
        order_type: 'custom',
        total_amount: 0, // Quote will be generated by Ana
        custom_description: formData.custom_description.trim(),
        reference_images: formData.reference_images,
      });
      setSuccess(true);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  if (success) {
    return (
      <main className="custom-order container">
        <div className="custom-order__success">
          <h2>¡Solicitud enviada!</h2>
          <p>Ana revisará tu solicitud y se pondrá en contacto contigo para confirmarte la viabilidad y cotizarte el costo final más el envío.</p>
          <Button onClick={() => setSuccess(false)}>Enviar otra solicitud</Button>
        </div>
      </main>
    );
  }

  return (
    <main className="custom-order container">
      <header className="custom-order__header">
        <h1 className="custom-order__title">Pedido Personalizado</h1>
        <p className="custom-order__subtitle">
          Cuéntanos qué tienes en mente. Ana evaluará tu diseño y te enviará una cotización (incluyendo el envío al Atlántico).
        </p>
      </header>

      <form className="form" onSubmit={handleSubmit}>
        {error && <div className="form__error">{error}</div>}
        
        <div className="form__group">
          <label htmlFor="customer_name">Nombre completo</label>
          <input required type="text" id="customer_name" name="customer_name" value={formData.customer_name} onChange={handleChange} />
        </div>
        
        <div className="form__row">
          <div className="form__group">
            <label htmlFor="customer_email">Correo electrónico</label>
            <input required type="email" id="customer_email" name="customer_email" value={formData.customer_email} onChange={handleChange} />
          </div>
          <div className="form__group">
            <label htmlFor="customer_phone">Teléfono (WhatsApp)</label>
            <input required type="tel" id="customer_phone" name="customer_phone" value={formData.customer_phone} onChange={handleChange} />
          </div>
        </div>

        <div className="form__row">
          <div className="form__group">
            <label htmlFor="address">Dirección de entrega</label>
            <input required type="text" id="address" name="address" value={formData.address} onChange={handleChange} placeholder="Ej. Calle 123 #45-67" />
          </div>
          <div className="form__group">
            <label htmlFor="department">Departamento</label>
            <select required id="department" name="department" value={formData.department} onChange={handleChange}>
              <option value="Atlantico">Atlántico</option>
              <option value="Otro" disabled>Otro (No disponible por ahora)</option>
            </select>
          </div>
        </div>

        <div className="form__group">
          <label htmlFor="custom_description">Describe tu idea</label>
          <textarea required id="custom_description" name="custom_description" rows="5" value={formData.custom_description} onChange={handleChange} placeholder="Detalla colores, tallas, estilo..."></textarea>
        </div>

        <div className="form__group">
          <label>Fotos de referencia (Opcional)</label>
          <div className="form__upload-area" style={{ position: 'relative' }}>
            <input 
              type="file" 
              multiple 
              accept="image/*" 
              onChange={handleImageUpload}
              disabled={uploading || loading}
              style={{
                position: 'absolute',
                top: 0, left: 0, right: 0, bottom: 0,
                opacity: 0,
                cursor: 'pointer'
              }}
              aria-label="Subir imágenes de referencia"
            />
            <Upload size={24} className="form__upload-icon" />
            <span>{uploading ? 'Subiendo imágenes...' : 'Haz clic o arrastra imágenes aquí'}</span>
          </div>
          
          {formData.reference_images.length > 0 && (
            <div className="custom-order__gallery" style={{ display: 'flex', gap: 'var(--space-2)', marginTop: 'var(--space-2)', flexWrap: 'wrap' }}>
              {formData.reference_images.map((url, idx) => (
                <div key={idx} style={{ position: 'relative', width: '80px', height: '80px' }}>
                  <img src={url} alt={`Referencia ${idx+1}`} style={{ width: '100%', height: '100%', objectFit: 'cover', borderRadius: 'var(--radius-sm)' }} />
                  <button
                    type="button"
                    onClick={() => removeImage(idx)}
                    style={{ position: 'absolute', top: -5, right: -5, background: 'var(--color-error)', color: '#fff', border: 'none', borderRadius: '50%', padding: '2px', cursor: 'pointer' }}
                    aria-label="Eliminar imagen"
                  >
                    <X size={14} />
                  </button>
                </div>
              ))}
            </div>
          )}
        </div>

        <Button type="submit" fullWidth disabled={loading || uploading} icon={Send}>
          {loading ? 'Enviando...' : 'Enviar solicitud de cotización'}
        </Button>
      </form>
    </main>
  );
}
